config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  get 'comments/show'
  get 'comments/create'
  get 'comments/destroy'
  get 'comments/new'
  root 'images#index'
  resources :images, only: [:create, :show] do
    resources :comments
  end
  get 'profile' => 'profile#show'
  devise_for :users
  resources :users, only: [:show]
  # get 'users/:id' => 'users#show', as: :user
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :image
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pictures
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :sanitize_devise_params, if: :devise_controller?

  def sanitize_devise_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_image, only: [:create, :destroy, :edit, :update]
 
  def index
  end

  def show
  end

  def edit
    @comment = Comment.find(params[:id]) 
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(description: params[:description])
    redirect_to image_path(@image)
  end

  def create
    @comment = Comment.create(description: params[:description], image:@image, user: current_user)
    redirect_to image_path(@image)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.delete
    redirect_to image_path(@image)
  end

  def new
  end
  private

  def set_image
    @image = Image.find(params[:image_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    puts @users
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def create
  #@encoding = Base64.strict_encode64(params[:images].path)
  @encoding= Base64.strict_encode64(File.open(params[:stream].tempfile).read)
  @description = params[:description]
  @extension = params[:stream].content_type
    if params[:private].present?
      @private = true
    else
      @private= false
    end
    @image = Image.create(stream: @encoding, private: @private, extension: @extension, description: @description, user:current_user)
    redirect_to root_path
  end

  def new
    @user = current_user
  end

  def show
    @image = Image.find(params[:id])
    @comments = @image.comments
  end

  def index
    @images = Image.all
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    def create
      @user = current_user
      @user.pictures.attach(params[:pictures])
      redirect_to(user_path(@user))
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
 

  def show
    @user=current_user
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :set_user, only: [:show] 

  def index
  end

  def show

  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
	<%= form_tag url_for(action: 'update'), method: "patch", multipart: true do %>
    <div class="form-group">
        <h5 class="text-primary">Your comment</h5>
        <%= text_area_tag 'description', @comment.description, class: "form-control", placeholder: "Description" %>
    </div>
    <div>
        <%= submit_tag "edit comment", class: "btn btn-primary mt-3 mb-3 " %>
    </div>
<% end %>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/home/index.html.erb
<h3>Ajoutez des images </h3>
<%= form_tag pictures_path, multipart: true do %>
  <%= file_field_tag :pictures %>
  <%= submit_tag "Ajouter" %>
<% end %>

<h3>Mes images</h3>

<% @users.each do |user|%>
  <%if user.pictures.attached?%>
    <% user.pictures.each do |picture| %>
      <%= image_tag(picture) %>
    <% end %>
  <%else%>
    <p>=== Il n'y a pas encore d'image lié à cet utilisateur ===</p>
  <%end%>
<%end%>

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/index.html.erb
<div class="container">
  <div class="p-5 m-5 card">
    <h3>Ajoutez des images </h3>
    <%= form_tag images_path, class:"row",  multipart: true do %>
      <%= file_field_tag :stream, class:"col-md-3" %>
      <label class="category-select">
      <%= check_box_tag :private, label:"private", class:"col-md-3" %>
      private
    </label>
      
      <%= text_field_tag :description, '',  placeholder: "description", class:"col-md-3" %>
      <%=  submit_tag "Ajouter", class: "col-md-3 btn btn-info" %>
    <% end %>
  </div>
  <div class="row">
    <% if @images != nil && @images != "" %>
    <% @images.each do |image| %>
      
      <% if image.user != current_user && image.private == true%>
      <%else%>
        <div class="col-md-3 card">
        <%= link_to image_tag("data:image/#{image.extension};base64,#{image.stream}", class:"flexible"), image_path(image) %>
          <div class="card-body">
            <p class="card-text"><%=image.description%></p>
          </div>
        </div>
      <%end%>

    <% end %>
    <%end%>
  </div>
</div>

app/views/images/show.html.erb
<div class="container">
<%= image_tag("data:image/#{@image.extension};base64,#{@image.stream}")%>

<h3> Add commment</h3>
  <div class="m-5 p-5">
    <%= form_tag image_comments_path(@image),   multipart: true do %>
      <%= text_area_tag :description, '',  placeholder: "Your comment" %>
      <%=  submit_tag "Add comment", class: "btn btn-info" %>
    <% end %>
  </div>
  <div>
  <% @comments.each do |comment|%>
  <p><%= comment.description%> | <%= comment.user.username%>
  <%if comment.user == current_user %>
    <%=link_to 'Delete', image_comment_path(@image, comment),data: {confirm: "Are you sure  ?"},  class:"btn btn-danger", method: :delete%>
     <%=link_to 'Edit', edit_image_comment_path(@image, comment), class:"btn btn-warning", method: :get%>
  <%end%>
  </p>

  <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">  
    <%= link_to 'Sign In',  new_user_session_path, class: "nav-item nav-link"  %>
    <%= link_to 'Sign Up',  new_user_registration_path, class: "nav-item nav-link" %>
    <%= link_to 'Sign Out', destroy_user_session_path,  method: :delete, class:"nav-item nav-link" %>
    
     <% if user_signed_in? %>
    <%= link_to 'My profile',  profile_path, class: "nav-item nav-link" %>
     <span class="nav-item nav-link"><%= current_user.username%></span> 
     <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageWithWebpack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pictures/create.html.erb
<h1>Pictures#create</h1>
<p>Find me in app/views/pictures/create.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<lu>
<li><%= @user.username %></li>
<li><%= @user.first_name %></li>
<li><%= @user.last_name[0] %></li>
</lu>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>